=== champix56/2023-02-caxcv1/photo.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSpy v2013 sp1 (http://www.altova.com) by ï»¿champix (champix) -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" attributeFormDefault="unqualified">
<!--include pour reprise du format de mail avec pattern-->
<xs:include schemaLocation="client.xsd"/>
	<xs:attribute name="titre" type="xs:boolean"/>
	<xs:attribute name="path" type="xs:string"/>
	<xs:element name="titre" type="xs:string"/>
	<!--groupe d'attrib de les balises image-->
	<xs:attributeGroup name="imageAttrib">
		<xs:annotation>
			<xs:documentation>image attributes couv and page</xs:documentation>
		</xs:annotation>
		<xs:attribute ref="path" use="required"/>
		<xs:attribute name="href" type="xs:string" use="required"/>
	</xs:attributeGroup>
	<!--types pour balise image-->
	<xs:complexType name="CT_couv_image">
		<xs:annotation>
			<xs:documentation>Type pour l'image de couverture</xs:documentation>
		</xs:annotation>
		<xs:attributeGroup ref="imageAttrib"/>
	</xs:complexType>
	<xs:complexType name="CT_page_image">
		<xs:annotation>
			<xs:documentation>Type pour les image des page</xs:documentation>
		</xs:annotation>
		<xs:simpleContent>
			<xs:extension base="xs:string">
				<xs:attributeGroup ref="imageAttrib"/>
			</xs:extension>
		</xs:simpleContent>
	</xs:complexType>
	<!--section signature-->
	<xs:simpleType name="ST_tel">
		<xs:restriction base="xs:string">
			<xs:pattern value="0[1-8]([. -]?\d{2}){4}"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:element name="mail" type="ST_mail"/>
	<xs:element name="tel" type="ST_tel"/>
	<xs:complexType name="CT_signature">
		<xs:sequence>
			<xs:element ref="mail"/>
			<xs:element ref="tel"/>
		</xs:sequence>
	</xs:complexType>
	<xs:element name="signature" type="CT_signature"/>
	<!--section page-->
	<xs:complexType name="CT_page">
		<xs:sequence>
			<xs:element name="image" type="CT_page_image" maxOccurs="4"/>
		</xs:sequence>
	</xs:complexType>
	<xs:element name="page" type="CT_page"/>
	<!--section pages-->
	<xs:complexType name="CT_pages">
		<xs:sequence>
			<xs:element ref="page" maxOccurs="unbounded"/>
		</xs:sequence>
		<xs:attribute ref="titre" use="required"/>
	</xs:complexType>
	<xs:element name="pages" type="CT_pages"/>
	<!--section couv-->
	<xs:complexType name="CT_couv">
		<xs:sequence>
			<xs:element name="image" type="CT_couv_image"/>
		</xs:sequence>
	</xs:complexType>
	<xs:element name="couv" type="CT_couv"/>
	<!--section photos-->
	<!--groupe d'attrib de la balise root-->
	<xs:attributeGroup name="rootAttrib">
		<xs:annotation>
			<xs:documentation>photos root attributes</xs:documentation>
		</xs:annotation>
		<xs:attribute name="theme" type="xs:string" use="required"/>
		<xs:attribute name="intercal" type="xs:boolean" use="required"/>
		<xs:attribute name="OnlyComment" type="xs:boolean" use="required"/>
	</xs:attributeGroup>
	<xs:complexType name="CT_photos">
		<xs:sequence>
			<xs:element ref="titre"/>
			<xs:element ref="couv"/>
			<xs:element ref="pages"/>
			<xs:element ref="signature"/>
		</xs:sequence>
		<xs:attributeGroup ref="rootAttrib"/>
	</xs:complexType>
	<xs:element name="photos" type="CT_photos"/>
</xs:schema>

=== champix56/2023-02-caxcv1/photo.xml
<?xml version="1.0" encoding="UTF-8"?>
<photos theme="C:\Documents and Settings\Administrateur\Application Data\fond1372366265.png" OnlyComment="false" intercal="true" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="photo.xsd">
	<titre>Album Photo web de Alex</titre>
	<couv>
		<image href="MG_1932_DxOEPREUVE-EPRUVEL.jpg" path="http://clanphs.free.fr/wp-content/uploads/"/>
	</couv>
	<pages titre="true">
		<page>
			<image href="Canon-EOS-5D-Mark-IIIH97C9470RS-L.jpg" path="http://clanphs.free.fr/wp-content/uploads/">firework</image>
			<image href="10599489_10152664721102884_8998763423280924639_n.jpg" path="http://clanphs.free.fr/wp-content/uploads/">fire2</image>
			<image href="10616075_10152664721277884_204613508926358332_n.jpg" path="http://clanphs.free.fr/wp-content/uploads/">Fire Locamariaquer</image>
			<image href="10637686_10152666826427884_326359702_n.jpg" path="http://clanphs.free.fr/wp-content/uploads/">fire versailles</image>
		</page>
		<page>
			<image href="10637762_10152666826227884_1150744547_n.jpg" path="http://clanphs.free.fr/wp-content/uploads/">versailles</image>
			<image href="10643440_10152666821127884_1257003855_n-688x457.jpg" path="http://clanphs.free.fr/wp-content/uploads/">versailles 4</image>
			<image href="10659229_10152664721312884_1912826066174067960_n.jpg" path="http://clanphs.free.fr/wp-content/uploads/">loc</image>
			<image href="ChampsChanvre-s.jpg" path="http://clanphs.free.fr/wp-content/uploads/">loc3</image>
		</page>
		<page>
			<image href="11313_10152664722977884_68115858871786570_n.jpg" path="http://clanphs.free.fr/wp-content/uploads/"/>
			<image href="934819_10152664725362884_952774551003375319_n-688x458.jpg" path="http://clanphs.free.fr/wp-content/uploads/"/>
			<image href="H97C6399-Copier.jpg" path="http://clanphs.free.fr/wp-content/uploads/"/>
			<image href="H97C6499-Copier.jpg" path="http://clanphs.free.fr/wp-content/uploads/"/>
		</page>
		<page>
			<image href="H97C9306FINAL-EPREUVE-EPRUVE-L.jpg" path="http://clanphs.free.fr/wp-content/uploads/"/>
			<image href="MG_0157_8_9_tonemappedEPRUVE-EPRUVEL.jpg" path="http://clanphs.free.fr/wp-content/uploads/"/>
			<image href="MG_0750EPREUVE-EPRUVEL.jpg" path="http://clanphs.free.fr/wp-content/uploads/"/>
			<image href="MG_1932_DxOEPREUVE-EPRUVEL.jpg" path="http://clanphs.free.fr/wp-content/uploads/">Paris</image>
		</page>
		<page>
			<image href="MG_1936_DxOepreuve-EPRUVEL.jpg" path="http://clanphs.free.fr/wp-content/uploads/"/>
			<image href="quiberonCoteSauvage-688x458.jpg" path="http://clanphs.free.fr/wp-content/uploads/"/>
			<image href="SH97C9989.jpg" path="http://clanphs.free.fr/wp-content/uploads/">Traffic jam</image>
			<image href="s_H97C0775.jpg" path="http://clanphs.free.fr/wp-content/uploads/"/>
		</page>
		<page>
			<image href="s_H97C1010.jpg" path="http://clanphs.free.fr/wp-content/uploads/"/>
			<image href="S_H97C7350b.jpg" path="http://clanphs.free.fr/wp-content/uploads/"/>
			<image href="S_H97C9008.jpg" path="http://clanphs.free.fr/wp-content/uploads/"/>
			<image href="S_H97C9131.jpg" path="http://clanphs.free.fr/wp-content/uploads/"/>
		</page>
		<page>
			<image href="S_H97C9173.jpg" path="http://clanphs.free.fr/wp-content/uploads/">Pont chartres</image>
			<image href="S_H97C9193.jpg" path="http://clanphs.free.fr/wp-content/uploads/"/>
		</page>
	</pages>
	<signature>
		<mail>desorbaix@free.fr</mail>
		<tel>06.64.27.63.60</tel>
	</signature>
</photos>
